name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Ini akan menjalankan action setiap hari
  workflow_dispatch: # Ini memungkinkan Anda menjalankan action secara manual
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: purna888 # Ganti dengan nama pengguna GitHub Anda
          outputs: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
